### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by noams24** [noams24/Kef-Code#16]
When uncommenting `const session = await getServerSession(authOptions);` from the file src/layouts/partials/Header.tsx,
I get an error if I deploy the app to Vercel:
```
Error: ENOENT: no such file or directory, open 'src/content/_index.md'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at readFile (/var/task/.next/server/chunks/3230.js:1430:54)
    at getListPage (/var/task/.next/server/chunks/3230.js:1443:22)
    at Home (/var/task/.next/server/app/page.js:466:58)
    at T (/var/task/.next/server/chunks/7388.js:16571:13)
    at Xa (/var/task/.next/server/chunks/7388.js:16676:21)
    at Array.toJSON (/var/task/.next/server/chunks/7388.js:16490:20)
    at stringify (<anonymous>)
    at hb (/var/task/.next/server/chunks/7388.js:16886:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'src/content/_index.md'
}
Error: ENOENT: no such file or directory, open 'src/content/pages/404.md'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at readFile (/var/task/.next/server/chunks/3230.js:1430:54)
    at getListPage (/var/task/.next/server/chunks/3230.js:1443:22)
    at NotFound (/var/task/.next/server/chunks/3230.js:995:90)
    at T (/var/task/.next/server/chunks/7388.js:16571:13)
    at Xa (/var/task/.next/server/chunks/7388.js:16676:21)
    at Array.toJSON (/var/task/.next/server/chunks/7388.js:16490:20)
    at stringify (<anonymous>)
    at hb (/var/task/.next/server/chunks/7388.js:16886:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'src/content/pages/404.md'
}
Error: ENOENT: no such file or directory, open 'src/content/pages/404.md'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at readFile (/var/task/.next/server/chunks/3230.js:1430:54)
    at getListPage (/var/task/.next/server/chunks/3230.js:1443:22)
    at NotFound (/var/task/.next/server/chunks/3230.js:995:90)
    at T (/var/task/.next/server/chunks/7388.js:16571:13)
    at Xa (/var/task/.next/server/chunks/7388.js:16676:21)
    at Object.toJSON (/var/task/.next/server/chunks/7388.js:16490:20)
    at stringify (<anonymous>)
    at hb (/var/task/.next/server/chunks/7388.js:16886:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'src/content/pages/404.md'
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '201210539'
}
```

In my opinion the problem is in this file:
![image](https://github.com/noams24/Kef-Code/assets/80849999/e088866a-c359-4f53-acc0-f30207a3ca4d)
Someone on discord wrote:
"On vercel and many platforms, this only works during build time, since those platforms don’t preserve the files after build"

**Comment by noams24** [comment]
fixed
